apiVersion: v1
data:
  HARBOR_PROJECTS: rancher
  HARBOR_REGISTRY: https://harbor.warnerchen.com
  HARBOR_TAGS: rc,test,patch,hotfix,alpha,sha256
  HARBOR_USERNAME: harbor-cleaner
kind: ConfigMap
metadata:
  name: harbor-cleaner
  namespace: default
